#!/bin/bash

source /root/installer/patcher/conf/conf.txt

set -o errexit

echo .
echo ============ Going to reinstall ==============

echo .
read -p "Are you fucking sure? " -n 1 -r

if [[ $REPLY =~ ^[Yy]$ ]]; then
  
  commit-all
  
  read -p "Make new reinstaller? " -n 1 -r makenew
  if [[ ! $makenew =~ ^[YyNn]$ ]]
  then
    echo "You did not enter y or n. Exiting"
    exit
  fi

  echo .
  echo "----- You have 5 seconds to control-C to cancel.... -------"
  countdown 5
  
  if [[ $makenew =~ ^[Yy]$ ]]
  then
    echo .
    echo "----------------------------------------------------"
    echo "Running ~/installer/patcher/bin/make_reinstaller ..."
    echo "----------------------------------------------------"
    ~/installer/patcher/bin/make_reinstaller
    echo .
    echo "----------------------------------------------------"
    echo "Deleting contents of /boot/ ..."
    echo "----------------------------------------------------"
    rm -rf /boot/*
    echo .
    echo "----------------------------------------------------"
    echo "Copying from the reinstall dir to /boot/..."
    echo "    from: $REINSTALLER_DIR/"
    echo "    to:   /boot/"
    echo "  ..."
    echo "----------------------------------------------------"
    cp -rf $REINSTALLER_DIR/* /boot/
  else
    cp /boot/config-reinstall.txt /boot/config.txt
  fi
  
  echo .
  echo "----- Reinstalling in 5 seconds .... -------"
  countdown 5

  shutdown -r now
  
fi

